{% set version = "4.2.0" %}
{% set posix = 'm2-' if win else '' %}

package:
  name: r-irace
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/irace_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/irace/irace_{{ version }}.tar.gz
  sha256: 58cfe6487141981a79411557e709061ffafca15a36289a71dd4e50a8afe4a7b1

build:
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/
  missing_dso_whitelist:
    - '*/R.dll'        # [win]
    - '*/Rblas.dll'    # [win]
    - '*/Rlapack.dll'  # [win]

requirements:
  build:
    - {{ compiler('c') }}        # [not win]
    - {{ stdlib("c") }}          # [not win]
    - {{ compiler('m2w64_c') }}  # [win]
    - {{ stdlib("m2w64_c") }}    # [win]
    - {{ posix }}filesystem      # [win]
    - {{ posix }}make
    - {{ posix }}sed             # [win]
    - {{ posix }}coreutils       # [win]
    - {{ posix }}zip             # [win]
  host:
    - r-base
    - r-r6
    - r-codetools
    - r-data.table >=1.15.0
    - r-fs
    - r-matrixstats >=1.4.1
    - r-spacefillr
    - r-withr
  run:
    - r-base
    - r-r6
    - r-codetools
    - r-data.table >=1.15.0
    - r-fs
    - r-matrixstats >=1.4.1
    - r-spacefillr
    - r-withr

test:
  commands:
    - $R -e "library('irace')"           # [not win]
    - "\"%R%\" -e \"library('irace')\""  # [win]

about:
  home: http://iridia.ulb.ac.be/irace
  dev_url: https://github.com/MLopez-Ibanez/irace
  license: GPL-2.0-or-later
  summary: Iterated race is an extension of the Iterated F-race method for the automatic configuration of optimization algorithms, that is, (offline) tuning their parameters by finding the most appropriate settings given a set of instances of an optimization problem.
  license_family: GPL
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-2
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3

extra:
  recipe-maintainers:
    - conda-forge/r
    - xhochy
