travis:
  secure:
    BINSTAR_TOKEN: M4f5A7AsEAOuwN9skFSA65fKQo28S0uzhrz3YLWX20tEdUO9ErhF/Zpk8WE6mij9+Wqxx67EUED4zNJ/oSpV6xFCF7dx6os+QmfW6T6skVygnutuIoMKuf0J9qGjh6xF7r9+ITcCrVLSAsBou6VjC57iU9uTWNGdbF1DC3rpyzIMEyEuHDPI1a0Sd8LhYw+NI4p+Em96msbFnjR85R/DnIwvBnDevnNClhATVI6gylgIgAX3yfc8n4lJDZavsqE3X5owYxE7T2RR8kRymDTa/Dl/O/+ngwLV8DNfBy6o5AE25WIflMclpgX0uSpjUZw1PIXq2t0/J2MlPCAH7qEWU6b2r5EEhrEehy5kOwL62ggAmnxvo1NTq9FUSWnvxt1yRvQ6/chiSljvdcQoqKeuVJ/SiXkBm7iQx5SGPLNOSXDOLR/jXC7XXVa2sSYKZL2fqN77L8Mwz/qNAzjjBVcnpkLL9pgAK3ISV6g29kMrDNjqxkEZNBHVWBzq7j9+k5APZ+3v3fud63SmOF4KDx0ymltkfUCTm350agtYBcvC4xlnMvFdagTxFFN428PZEYMqkTSyVzUS0qfS2wU6tdU25sR8ED89736uQAIZcZkyT1nd4+tUhZhgrv9RzarMoKMzO/ItgSg1Ru3GUjYSFzegxbhI5C1gTU6Tx2IjMq1V6fE=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
