appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
bot:
  automerge: true
provider:
  win: azure
travis:
  secure:
    BINSTAR_TOKEN: ZjaUeqBV2UxcTK+Dm5lP2zX35gNpu/awU+SHxcM7bLQHm+5Ou6lSGpBa4H9QWZ4AFkhSbgtai9DON7kS9visrNmmhR8dtDfmQlOAQktdH8YO/yQrL1wRu0mwThHP1gm4RB8Vn3ngBMYjbC6xcOgKxug9SKwLHtOwQU9SOq0xwH+YCAUWhiq1SHbA1hG39lgvKnWbeaDHvRpVkm9YB7myLhog3U7Vh7zMPEjJZ2TDax8Kf6xGg5XIF+qLkAB38b8NIDWJfQ5+O/MsR7/AmxGVwrbc++UWtIuO8B6C6VOxBnZfXDWMCHaD79X9O2Dr6H2WE8axMuj8oX0Hvv0s4dQtmv5RGyCCfQDXITH2M8/NCwTWbzGSNZHh0K5KVhBeKqBzpOcZAmSXnioXm9p6KGejgNCo/tq+Q0FDWxAYmqi2WczB43yvAhHCRZk75Mf9K7vmzvmceNOZKZvP38tHUjfnxx7blM7tmjmS3IDDT3pt/wYOVMf0S68XkV8CpjmNKtr72bCugoheO1G+Z27dP13ugkVzUsh+K4H2UvM5hgXUOPZoVHUb18XsRhVzlvonwZmR6vsa+W93R3a3ZbCQKLAfIa8ArX5Y7WtZvMMNGrvep2wkakYKni6gq8j19iqnsZPYvKUhEj5pzjO7IeUYm5D5x2hyr4oaMti0b5VhGoNh6lU=
conda_forge_output_validation: true
